# -*- coding: utf-8 -*-
"""FL_based_IOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvZVU2NYQU9UFFnFiduywOnMs_U1wmNq
"""

# !pip install torch

# !pip install shap

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import random
import math
import time
import os
import matplotlib.pyplot as plt
from collections import deque
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report, confusion_matrix, balanced_accuracy_score, matthews_corrcoef, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif, VarianceThreshold
from sklearn.impute import SimpleImputer
from torch.utils.data import TensorDataset, DataLoader
import copy
import joblib
import gc
import shap
import warnings
warnings.filterwarnings('ignore')

SEQUENCE_LENGTH = 10

# Set random seeds for reproducibility
np.random.seed(42)
torch.manual_seed(42)
random.seed(42)

# Data Preprocessing Class (Fit/Transform Pattern to Prevent Data Leakage)
class preprocess_data():
    def __init__(self):
        self.le = {}
        self.ss = {}
        self.imputers = {}
        self.inf_means = {}
        self.num_cols = []
        self.cat_cols = []
        self.features = []
        self.target = ""
        self.high_cardinality_cols = []
        self.low_cardinality_cols = []
        self.dummy_columns = []
        self.selected_features = []
        
        self.variance_threshold_mask = None
        self.select_k_best_selector = None
        
        self.outlier_medians = {}
        self.outlier_bounds = {}

    def fit(self, df, k=25):
        df = df.copy()
        
        self.target = 'Label' if 'Label' in df.columns else df.columns[-1]
        self.features = [col for col in df.columns if col not in [self.target, 'Attack_categories']]
        
        num_cols = df[self.features].select_dtypes(include=np.number).columns.tolist()
        cat_cols = df[self.features].select_dtypes(include=['object']).columns.tolist()
        self.num_cols = num_cols
        self.cat_cols = cat_cols
        
        # 1. Handle infinite values
        for col in df.columns:
            if pd.api.types.is_numeric_dtype(df[col]):
                finite_vals = df[col][np.isfinite(df[col])]
                mean_val = finite_vals.mean() if len(finite_vals) > 0 else 0.0
                self.inf_means[col] = mean_val
                df[col] = df[col].replace([np.inf, -np.inf], mean_val)
                
        # 2. Impute numerical
        for col in self.num_cols:
            if col == self.target:
                continue
            imputer = SimpleImputer(strategy='mean')
            df[[col]] = imputer.fit_transform(df[[col]])
            self.imputers[col] = imputer
            
        # 3. Impute categorical
        for col in self.cat_cols:
            if col == self.target:
                continue
            imputer = SimpleImputer(strategy='most_frequent')
            df[[col]] = imputer.fit_transform(df[[col]])
            self.imputers[col] = imputer
            
        # 4. Categorical cardinality separation
        for col in self.cat_cols:
            unique_vals = df[col].nunique()
            if unique_vals > 10:
                self.high_cardinality_cols.append(col)
            else:
                self.low_cardinality_cols.append(col)
                
        # 5. Label encode high-cardinality
        for col in self.high_cardinality_cols:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col].astype(str))
            self.le[col] = le
            
        # 6. One-hot encode low-cardinality
        df_encoded = pd.get_dummies(df, columns=self.low_cardinality_cols, drop_first=True)
        encoded_features = [c for c in df_encoded.columns if c not in [self.target, 'Attack_categories']]
        self.dummy_columns = [c for c in df_encoded.columns if c != self.target and c != 'Attack_categories']
        
        # 7. Fit outlier bounds on numerical columns
        encoded_num_cols = df_encoded[encoded_features].select_dtypes(include=np.number).columns.tolist()
        for col in encoded_num_cols:
            Q1 = df_encoded[col].quantile(0.25)
            Q3 = df_encoded[col].quantile(0.75)
            IQR = Q3 - Q1
            self.outlier_bounds[col] = (Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)
            self.outlier_medians[col] = df_encoded[col].median()
            
            lower, upper = self.outlier_bounds[col]
            outliers = (df_encoded[col] < lower) | (df_encoded[col] > upper)
            df_encoded.loc[outliers, col] = self.outlier_medians[col]
            
        # 8. Fit standard scaling
        for col in encoded_num_cols:
            scaler = StandardScaler()
            df_encoded[[col]] = scaler.fit_transform(df_encoded[[col]])
            self.ss[col] = scaler
            
        # 9. Fit feature selection
        if df_encoded[self.target].dtype == 'object':
            target_le = LabelEncoder()
            df_encoded[self.target] = target_le.fit_transform(df_encoded[self.target])
            self.le[self.target] = target_le
            
        # Remove constant features
        vt = VarianceThreshold(threshold=0.0)
        vt.fit(df_encoded[encoded_features])
        self.variance_threshold_mask = vt.get_support()
        features_vt = [col for col, keep in zip(encoded_features, self.variance_threshold_mask) if keep]
        
        # Select K best features
        selector = SelectKBest(score_func=f_classif, k=min(k, len(features_vt)))
        selector.fit(df_encoded[features_vt], df_encoded[self.target])
        self.select_k_best_selector = selector
        
        self.selected_features = [feat for feat, keep in zip(features_vt, selector.get_support()) if keep]
        
    def transform(self, df):
        df = df.copy()
        
        # 1. Handle infinite values
        for col in df.columns:
            if pd.api.types.is_numeric_dtype(df[col]) and col in self.inf_means:
                df[col] = df[col].replace([np.inf, -np.inf], self.inf_means[col])
                
        # 2. Impute numerical & categorical
        for col, imputer in self.imputers.items():
            if col in df.columns:
                df[[col]] = imputer.transform(df[[col]])
                
        # 3. Label encode high-cardinality
        for col in self.high_cardinality_cols:
            if col in df.columns:
                le = self.le[col]
                df[col] = df[col].astype(str)
                classes_dict = {cls: idx for idx, cls in enumerate(le.classes_)}
                df[col] = df[col].apply(lambda val: classes_dict.get(val, 0))
                
        # 4. One-hot encode low-cardinality
        has_target = self.target in df.columns
        target_col = df[self.target].values if has_target else None
        
        df_encoded = pd.get_dummies(df, columns=self.low_cardinality_cols, drop_first=True)
        df_encoded = df_encoded.reindex(columns=self.dummy_columns, fill_value=0)
        
        # 5. Handle outliers
        for col, bounds in self.outlier_bounds.items():
            if col in df_encoded.columns:
                lower, upper = bounds
                outliers = (df_encoded[col] < lower) | (df_encoded[col] > upper)
                df_encoded.loc[outliers, col] = self.outlier_medians[col]
                
        # 6. Standard scaling
        for col, scaler in self.ss.items():
            if col in df_encoded.columns:
                df_encoded[[col]] = scaler.transform(df_encoded[[col]])
                
        # 7. Extract selected features
        X_selected = df_encoded[self.selected_features].values.astype(np.float32)
        
        if has_target:
            if pd.api.types.is_object_dtype(target_col):
                if self.target in self.le:
                    target_col = self.le[self.target].transform(target_col)
                else:
                    target_col = LabelEncoder().fit_transform(target_col)
            y_selected = target_col.astype(np.int64)
        else:
            y_selected = None
            
        return df_encoded[self.selected_features], X_selected, y_selected

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1), :]

class MiniTransformerAutoencoder(nn.Module):
    def __init__(self, input_dim, latent_dim=32, n_heads=2, ff_dim=64, n_layers=2, seq_len=10):
        super(MiniTransformerAutoencoder, self).__init__()
        self.seq_len = seq_len
        self.input_dim = input_dim
        self.embedding = nn.Linear(input_dim, ff_dim)
        self.pos_encoder = PositionalEncoding(ff_dim, max_len=seq_len)
        # self.classifier = nn.Linear(latent_dim, 2)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=ff_dim,
            nhead=n_heads,
            dim_feedforward=ff_dim,
            dropout=0.1,
            activation='relu',
            batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)

        self.encoder_fc = nn.Linear(ff_dim, latent_dim)
        self.decoder_fc = nn.Linear(latent_dim, ff_dim)
        self.output_layer = nn.Linear(ff_dim, input_dim)
    def get_weights(self):
        return {k: v.cpu().detach().clone() for k, v in self.state_dict().items()}

    def set_weights(self, weights):
        self.load_state_dict(weights)

    def forward(self, x):
        # Encode
        x = self.embedding(x)                     # (batch, seq_len, ff_dim)
        x = self.pos_encoder(x)                   # Add positional encoding
        x = self.transformer_encoder(x)           # Transformer encoder
        latent_seq = self.encoder_fc(x)           # (batch, seq_len, latent_dim)

        # Use Mean Pooling over the sequence time dimension
        latent_vector = latent_seq.mean(dim=1)      # (batch, latent_dim)

        # Classification output
        # logits = self.classifier(latent_vector)   # (batch, 2)

        # Decode (broadcast latent back over time)
        repeated_latent = latent_vector.unsqueeze(1).repeat(1, self.seq_len, 1)  # (batch, seq_len, latent_dim)
        x = self.decoder_fc(repeated_latent)      # (batch, seq_len, ff_dim)
        reconstructed = self.output_layer(x)      # (batch, seq_len, input_dim)

        return reconstructed

# Base class for all nodes in the IoT architecture
class Node:
    def __init__(self, node_id, name):
        self.node_id = node_id
        self.node_name = name
        self.parent = None
        self.children = []
        self.data_buffer = []
        self.last_update_time = time.time()

    def add_child(self, child):
        self.children.append(child)
        child.parent = self

    def send_data(self, data, destination):
        print(f"\n[{self.node_name}] Sending data to {destination.node_name}")
        destination.receive_data(data, self)

    def receive_data(self, data, source):
        print(f"\n[{self.node_name}] Received data from {source.node_name}\n")
        self.data_buffer.append(data)
        self.last_update_time = time.time()

    def evaluate_model(self, model, test_loader, threshold, device):
        model.to(device)
        model.eval()
        correct, total = 0, 0
        criterion = nn.MSELoss(reduction='none')
        all_preds = []
        all_targets = []
        all_mse = []

        with torch.no_grad():
            for X, y in test_loader:
                X, y = X.to(device), y.to(device)
                reconstructed = model(X)

                # Calculate MSE per sequence: mean over time and features
                mse = criterion(reconstructed, X).mean(dim=[1, 2])
                
                # Predict anomaly (1) if MSE exceeds threshold, else 0
                preds = (mse > threshold).long()
                
                total += y.size(0)
                correct += (preds == y).sum().item()
                
                all_preds.extend(preds.cpu().numpy())
                all_targets.extend(y.cpu().numpy())
                all_mse.extend(mse.cpu().numpy())

        accuracy = correct / total
        bal_acc = balanced_accuracy_score(all_targets, all_preds)
        mcc = matthews_corrcoef(all_targets, all_preds)
        
        try:
            roc_auc = roc_auc_score(all_targets, all_mse)
        except Exception as e:
            roc_auc = 0.0
            print(f"[{self.node_name}] Warning: Could not compute ROC-AUC: {e}")

        print(f"Accuracy: {accuracy:.4f}")
        print(f"Balanced Accuracy: {bal_acc:.4f}")
        print(f"Matthews Correlation Coefficient (MCC): {mcc:.4f}")
        print(f"ROC-AUC: {roc_auc:.4f}")
        print("Classification Report:")
        print(classification_report(all_targets, all_preds, target_names=["normal", "anomaly/attack"], zero_division=0))
        print("Confusion Matrix:")
        print(confusion_matrix(all_targets, all_preds))

    def create_sequences_with_labels(self, X, y, seq_len=10):
        sequences = []
        labels = []
        for i in range(len(X) - seq_len + 1):
            sequences.append(X[i:i+seq_len])
            labels.append(np.max(y[i : i + seq_len]))
        return np.array(sequences), np.array(labels)

    def create_test_sequences(self, X, seq_len=10):
        sequences = []
        for i in range(len(X) - seq_len + 1):
            sequences.append(X[i:i+seq_len])
        return np.array(sequences)

    def process_data(self):
        raise NotImplementedError("Subclasses must implement process_data()")


class Edge(Node):
    def __init__(self, node_id, name, local_df, X, y):
      super().__init__(node_id, name)
      self.df = local_df
      self.X = X
      self.y = y

      self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
      self.sequence_length = SEQUENCE_LENGTH
      self.epochs = 20  # Max epochs
      self.patience = 3  # Early stopping patience
      self.local_model = None
      self.global_model_weights = None
      self.local_model_weights = None
      self.input_dim = None
      self.num_training_samples = 0

    def receive_global_model(self, global_model_weights):
      print(f"[{self.node_name}] Received global model from Gateway.")
      self.global_model_weights = global_model_weights

    def process_data(self):
      # Generate sequence windows from all continuous traffic first (preserving temporal continuity)
      X_seq, y_seq = self.create_sequences_with_labels(self.X, self.y, self.sequence_length)
      
      # Keep only sequence windows that are 100% benign for training the unsupervised autoencoder
      # Windows containing attack packets are excluded from autoencoder training to ensure
      # the reconstruction model learns only the distribution of normal network behavior,
      # while all windows are retained for evaluation.
      benign_mask = (y_seq == 0)
      X_benign_seq = X_seq[benign_mask]
      
      num_malicious_discarded = np.sum(y_seq != 0)
      print(f"[{self.node_name}] Sequence windows built: {len(X_seq)} total windows. Keep {len(X_benign_seq)} normal windows. Exclude {num_malicious_discarded} attack windows from training.")
      
      self.input_dim = self.X.shape[1]
      print(f"[{self.node_name}] Input dimension: {self.input_dim}")

      if self.global_model_weights:
          self.local_model = MiniTransformerAutoencoder(
              input_dim=self.input_dim,
              latent_dim=32,
              ff_dim=64,
              n_heads=2,
              n_layers=2,
              seq_len=self.sequence_length
          ).to(self.device)
          self.local_model.set_weights(self.global_model_weights) # Loading global model
          print(f"\n[{self.node_name}] Loaded global model for fine-tuning.")
      else:
          self.local_model = MiniTransformerAutoencoder(
              input_dim=self.input_dim,
              latent_dim=32,
              ff_dim=64,
              n_heads=2,
              n_layers=2,
              seq_len=self.sequence_length
          ).to(self.device)
          print(f"[{self.node_name}] Training from scratch.") # Training local model

      print(f"[{self.node_name}] Started training!\n")

      # Generate sequences only from benign data
      if len(X_benign_seq) < self.sequence_length:
          raise ValueError(f"[{self.node_name}] Not enough normal samples to create sequences.")
          
      # Split sequence data into local Train (80%) and local Validation (20%)
      split_idx = int(0.8 * len(X_benign_seq))
      indices = np.arange(len(X_benign_seq))
      np.random.shuffle(indices)
      train_idx = indices[:split_idx]
      val_idx = indices[split_idx:]
      
      X_train_seq = X_benign_seq[train_idx]
      X_val_seq = X_benign_seq[val_idx]
      
      self.num_training_samples = len(X_train_seq)
      
      X_train_tensor = torch.tensor(X_train_seq, dtype=torch.float32)
      X_val_tensor = torch.tensor(X_val_seq, dtype=torch.float32).to(self.device)

      print(f"[DEBUG] Local Train sequences: {X_train_tensor.shape}, Local Validation: {X_val_tensor.shape}")

      # Training starts
      self.train_local_model(X_train_tensor, X_val_tensor, self.epochs, self.patience)

    def create_sequences(self, data, seq_len):
      sequences = []
      for i in range(len(data) - seq_len + 1):
          seq = data[i:i+seq_len]
          sequences.append(seq)
      return np.array(sequences)

    def train_local_model(self, X_train_tensor, X_val_tensor, max_epochs=20, patience=3):
      # Create DataLoader for training set to run mini-batch SGD
      train_dataset = TensorDataset(X_train_tensor)
      train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, pin_memory=True)
      
      # Instantiate AdamW optimizer with weight decay regularization
      optimizer = torch.optim.AdamW(self.local_model.parameters(), lr=0.001, weight_decay=1e-4)
      criterion = nn.MSELoss()
      
      best_val_loss = float('inf')
      best_weights = copy.deepcopy(self.local_model.state_dict())
      epochs_without_improvement = 0
      best_epoch = 0

      for epoch in range(max_epochs):
          # Train epoch using mini-batches
          self.local_model.train()
          epoch_train_loss = 0.0
          for batch in train_loader:
              batch_x = batch[0].to(self.device)
              
              optimizer.zero_grad()
              output = self.local_model(batch_x)
              loss = criterion(output, batch_x)
              loss.backward()
              optimizer.step()
              
              epoch_train_loss += loss.item() * batch_x.size(0)
          
          epoch_train_loss /= len(X_train_tensor)
          
          # Validation epoch
          self.local_model.eval()
          with torch.no_grad():
              val_output = self.local_model(X_val_tensor)
              val_loss = criterion(val_output, X_val_tensor).item()
              
          if val_loss < best_val_loss:
              best_val_loss = val_loss
              best_weights = copy.deepcopy(self.local_model.state_dict())
              epochs_without_improvement = 0
              best_epoch = epoch + 1
          else:
              epochs_without_improvement += 1
              
          if epoch % 1 == 0 or epochs_without_improvement >= patience:
              print(f"[{self.node_name}] Epoch {epoch+1}/{max_epochs} | Train Loss: {epoch_train_loss:.4f} | Val Loss: {val_loss:.4f}")
              
          if epochs_without_improvement >= patience:
              print(f"[{self.node_name}] Early stopping triggered. Restoring best model weights from epoch {best_epoch} (Val Loss: {best_val_loss:.4f})")
              break
              
      self.local_model.load_state_dict(best_weights)
      print(f"[{self.node_name}] Final Local Validation Loss: {best_val_loss:.4f}")
      self.local_model_weights = self.local_model.get_weights()

    def send_model_weights(self):
      if self.parent:
          # Convert weights to float16 to simulate quantized communication
          quantized_weights = {k: v.to(torch.float16) for k, v in self.local_model_weights.items()}
          packet = {
              'node_id': self.node_id,
              'weights': quantized_weights,
              'num_samples': self.num_training_samples
          }
          self.send_data(packet, self.parent)


class Gateway(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.received_weights = {}
        self.global_model_weights = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.sequence_length = SEQUENCE_LENGTH
        self.input_dim = None
        self.local_model = None
        self.local_model_weights = None

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if 'weights' in data:
            self.received_weights[data['node_id']] = data

    def process_data(self):
        if self.parent:
            packets_list = list(self.received_weights.values())
            packet = {
                'node_id': self.node_id,
                'packets': packets_list
            }
            self.send_data(packet, self.parent)

    def receive_global_model(self, global_weights):
        self.global_model_weights = global_weights
        print(f"[{self.node_name}] Received global model from Fog.")
        for edge in self.children:
            edge.receive_global_model(global_weights)

    def eval(self, df, X, y, threshold):
        print(f"[{self.node_name}] Testing the local model received from edge devices!")

        if not self.received_weights:
            print(f"[{self.node_name}] No model weights available for testing!")
            return
            
        weights_to_test = list(self.received_weights.values())[0]['weights']
        
        self.df = df
        self.X = X
        self.y = y        

        # Get actual input dimension
        self.input_dim = self.X.shape[1]
        print(f"[{self.node_name}] Input dimension: {self.input_dim}")

        X_sampled = self.X
        y_sampled = np.array(self.y)

        # Convert and generate sequences
        X_seq, y_seq = self.create_sequences_with_labels(X_sampled, y_sampled, seq_len=self.sequence_length)

        X_test_tensor = torch.tensor(X_seq, dtype=torch.float32)
        y_test_tensor = torch.tensor(y_seq, dtype=torch.long)

        test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
        test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, pin_memory=True)

        # Create model with correct input dimension
        self.local_model = MiniTransformerAutoencoder(
            input_dim=self.input_dim,
            latent_dim=32,
            ff_dim=64,
            n_heads=2,
            n_layers=2,
            seq_len=self.sequence_length
        ).to(self.device)

        # Load the received weights
        self.local_model.set_weights(weights_to_test)
        print(f"[{self.node_name}] Model loaded successfully!")

        self.evaluate_model(self.local_model, test_loader, threshold, self.device)


class Fog(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.global_model_weights = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.global_model = None
        self.input_dim = 87
        self.sequence_length = SEQUENCE_LENGTH
        self.received_packets = []
        self.total_samples_under_fog = 0

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if isinstance(data, dict) and 'packets' in data:
            self.received_packets = data['packets']
        else:
            self.received_packets = []

    def aggregate_weights(self, packets_list):
        if not packets_list:
            raise ValueError(f"[{self.node_name}] No packets received for aggregation.")

        total_samples = sum(p.get('num_samples', 0) for p in packets_list)
        self.total_samples_under_fog = total_samples
        
        if total_samples == 0:
            print(f"[{self.node_name}] Warning: Total sample count is 0, using simple average.")
            total_samples = len(packets_list)
            weights_list = [p['weights'] for p in packets_list]
            avg_weights = {k: v.to(torch.float32) for k, v in weights_list[0].items()}
            for k in avg_weights:
                for i in range(1, len(weights_list)):
                    avg_weights[k] += weights_list[i][k].to(torch.float32)
                avg_weights[k] /= len(weights_list)
            return avg_weights

        # Weighted FedAvg
        first_packet = packets_list[0]
        n0 = first_packet.get('num_samples', 0)
        avg_weights = {k: (v.to(torch.float32) * n0) for k, v in first_packet['weights'].items()}

        for i in range(1, len(packets_list)):
            p = packets_list[i]
            n_k = p.get('num_samples', 0)
            for k in avg_weights:
                avg_weights[k] += p['weights'][k].to(torch.float32) * n_k

        for k in avg_weights:
            avg_weights[k] /= total_samples

        return avg_weights

    def process_data(self):
        if not hasattr(self, 'received_packets') or not self.received_packets:
            print(f"[{self.node_name}] No weights to aggregate.")
            return

        self.global_model_weights = self.aggregate_weights(self.received_packets)
        print(f"[{self.node_name}] Global model aggregated via Weighted FedAvg (Total samples: {self.total_samples_under_fog}). Sent to Cloud.\n")

        # Get input dimension dynamically
        for key in self.global_model_weights.keys():
            if 'embedding.weight' in key:
                self.input_dim = self.global_model_weights[key].shape[1]
                break

        if self.input_dim is None:
            print(f"[{self.node_name}] Warning: Could not determine input dimension, using default 87")
            self.input_dim = 87

        self.global_model = MiniTransformerAutoencoder(
            input_dim=self.input_dim,
            latent_dim=32,
            ff_dim=64,
            n_heads=2,
            n_layers=2,
            seq_len=self.sequence_length
        ).to(self.device)
        
        self.global_model.load_state_dict(self.global_model_weights)
        torch.save(self.global_model.state_dict(), "Global_Model_Fog.pth")
        
        for gateway in self.children:
            if hasattr(gateway, "receive_global_model"):
                gateway.receive_global_model(self.global_model_weights)

    def receive_global_model(self, global_model_weights):
        self.global_model_weights = global_model_weights
        for gateway in self.children:
            if hasattr(gateway, "receive_global_model"):
                gateway.receive_global_model(self.global_model_weights)

    def send_global_weights(self):
        if self.parent:
            packet = {
                'node_id': self.node_id,
                'weights': self.global_model_weights,
                'num_samples': self.total_samples_under_fog
            }
            self.send_data(packet, self.parent)

    def eval(self, df, X, y, threshold):
        print(f"[{self.node_name}] Testing the global model aggregated at Fog level!")

        if not self.global_model_weights:
            print(f"[{self.node_name}] No model weights available for testing!")
            return
        
        self.df = df
        self.X = X
        self.y = y        

        # Get actual input dimension
        self.input_dim = self.X.shape[1]
        print(f"[{self.node_name}] Input dimension: {self.input_dim}")

        X_sampled = self.X
        y_sampled = np.array(self.y)

        # Convert and generate sequences
        X_seq, y_seq = self.create_sequences_with_labels(X_sampled, y_sampled, seq_len=self.sequence_length)

        X_test_tensor = torch.tensor(X_seq, dtype=torch.float32)
        y_test_tensor = torch.tensor(y_seq, dtype=torch.long)

        test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
        test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, pin_memory=True)

        # Create model with correct input dimension
        self.local_model = MiniTransformerAutoencoder(
            input_dim=self.input_dim,
            latent_dim=32,
            ff_dim=64,
            n_heads=2,
            n_layers=2,
            seq_len=self.sequence_length
        ).to(self.device)

        # Load the received weights
        self.local_model.set_weights(self.global_model_weights)
        print(f"[{self.node_name}] Model loaded successfully!")

        self.evaluate_model(self.local_model, test_loader, threshold, self.device)


class Proxy(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.received_weights = None
        self.received_num_samples = 0
        self.global_model_weights = None
        self.global_model = []

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if 'weights' in data:
            self.received_weights = data['weights']
            self.received_num_samples = data.get('num_samples', 0)

    def process_data(self):
        if self.parent:
          packet = {
              'node_id': self.node_id,
              'weights': self.received_weights,
              'num_samples': self.received_num_samples
          }
          self.send_data(packet, self.parent)

    def receive_global_model(self, global_weights):
      self.global_model_weights = global_weights
      print(f"[{self.node_name}] Received global model from Cloud.")
      for fog in self.children:
        print(f"[{fog.node_name}] Received global model from Proxy.")
        fog.receive_global_model(global_weights)

class Cloud(Node):
    def __init__(self, node_id, name):
        super().__init__(node_id, name)
        self.global_model_weights = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.input_dim = None
        self.sequence_length = SEQUENCE_LENGTH
        self.global_model = None
        self.received_packets = []

    def receive_data(self, data, source):
        super().receive_data(data, source)
        if not hasattr(self, 'received_packets') or not isinstance(self.received_packets, list):
            self.received_packets = []
        if isinstance(data, dict) and 'weights' in data:
            self.received_packets.append(data)

    def aggregate_weights(self, packets_list):
        if not packets_list:
            raise ValueError(f"[{self.node_name}] No packets received for aggregation.")

        total_samples = sum(p.get('num_samples', 0) for p in packets_list)
        if total_samples == 0:
            print(f"[{self.node_name}] Warning: Total sample count is 0, using simple average.")
            total_samples = len(packets_list)
            weights_list = [p['weights'] for p in packets_list]
            avg_weights = {k: v.to(torch.float32) for k, v in weights_list[0].items()}
            for k in avg_weights:
                for i in range(1, len(weights_list)):
                    avg_weights[k] += weights_list[i][k].to(torch.float32)
                avg_weights[k] /= len(weights_list)
            return avg_weights

        # Weighted FedAvg
        first_packet = packets_list[0]
        n0 = first_packet.get('num_samples', 0)
        avg_weights = {k: (v.to(torch.float32) * n0) for k, v in first_packet['weights'].items()}

        for i in range(1, len(packets_list)):
            p = packets_list[i]
            n_k = p.get('num_samples', 0)
            for k in avg_weights:
                avg_weights[k] += p['weights'][k].to(torch.float32) * n_k

        for k in avg_weights:
            avg_weights[k] /= total_samples

        return avg_weights

    def process_data(self):
        if not hasattr(self, 'received_packets') or not self.received_packets:
            print(f"[{self.node_name}] No weights to aggregate.")
            return

        self.global_model_weights = self.aggregate_weights(self.received_packets)
        print(f"[{self.node_name}] Global model aggregated via Weighted FedAvg at Cloud. Now sent to Fog nodes.\n")
        
        self.received_packets = []

        # Get input dimension dynamically from weights
        for key in self.global_model_weights.keys():
            if 'embedding.weight' in key:
                self.input_dim = self.global_model_weights[key].shape[1]
                break

        if self.input_dim is None:
            print(f"[{self.node_name}] Warning: Could not determine input dimension, using default 87")
            self.input_dim = 87
        
        self.global_model = MiniTransformerAutoencoder(
            input_dim=self.input_dim,
            latent_dim=32,
            ff_dim=64,
            n_heads=2,
            n_layers=2,
            seq_len=self.sequence_length
        ).to(self.device)
    
        self.global_model.load_state_dict(self.global_model_weights)
        torch.save(self.global_model.state_dict(), "Global_Model_Cloud.pth")

        for proxy in self.children:
            if hasattr(proxy, "receive_global_model"):
                proxy.receive_global_model(self.global_model_weights)

    def eval(self, df, X, y, threshold):
        print(f"[{self.node_name}] Testing the final global model at Cloud level!")

        if not self.global_model:
            print(f"[{self.node_name}] No global model available for testing!")
            return
        
        self.df = df
        self.X = X
        self.y = y        

        # Get actual input dimension
        self.input_dim = self.X.shape[1]
        print(f"[{self.node_name}] Input dimension: {self.input_dim}")

        X_sampled = self.X
        y_sampled = np.array(self.y)

        # Convert and generate sequences
        X_seq, y_seq = self.create_sequences_with_labels(X_sampled, y_sampled, seq_len=self.sequence_length)

        X_test_tensor = torch.tensor(X_seq, dtype=torch.float32)
        y_test_tensor = torch.tensor(y_seq, dtype=torch.long)

        test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
        test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, pin_memory=True)

        self.evaluate_model(self.global_model, test_loader, threshold, self.device)

class Application(Node):
    def __init__(self, node_id, name, model_path, X_test, y_test, feature_names):
        super().__init__(node_id, name)
        self.model_path = model_path
        self.X_test = X_test
        self.y_test = y_test
        self.feature_names = feature_names
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = None
        self.X = None
        self.y = None

    def XAI(self):
        self.load_model_and_data()
        self.run_xai()

    def load_model_and_data(self):
        # We slice it to a smaller size for SHAP, because SHAP can be very slow
        sample_size = min(100, len(self.X_test))
        X_sampled = self.X_test[:sample_size]
        y_sampled = self.y_test[:sample_size]

        # Convert and generate sequences
        seq_len = SEQUENCE_LENGTH
        X_seq, y_seq = self.create_sequences_with_labels(X_sampled, y_sampled, seq_len=seq_len)

        self.X = X_seq
        self.y = y_seq

        input_dim = self.X.shape[2]  # use dim from sequence
        
        # Load the model
        try:
            self.model = torch.load(self.model_path, map_location=self.device, weights_only=False)
        except Exception as e:
            print(f"[{self.node_name}] Warning: Failed to load full model object: {e}. Trying to load state dict...")
            self.model = MiniTransformerAutoencoder(
                input_dim=input_dim,
                latent_dim=32,
                ff_dim=64,
                n_heads=2,
                n_layers=2,
                seq_len=seq_len
            ).to(self.device)
            try:
                self.model.load_state_dict(torch.load(self.model_path, map_location=self.device, weights_only=True))
            except Exception as e2:
                self.model.load_state_dict(torch.load(self.model_path, map_location=self.device, weights_only=False))
            
        self.model.eval()
        print(f"[{self.node_name}] Model loaded successfully for XAI.")

    def run_xai(self):
        if self.model is None or self.X is None:
            print(f"[{self.node_name}] Model or data not loaded. Run `load_model_and_data()` first.")
            return

        print(f"[{self.node_name}] Running XAI (SHAP Explainability for Anomaly Score)")

        # Prepare subset of test sequences for explanations
        background_data = self.X[:10]  # 10 background samples
        test_samples_subset = self.X[10:20]  # 10 samples to explain
        
        N_bg, seq_len, input_dim = background_data.shape
        bg_flat = background_data.reshape(N_bg, seq_len * input_dim)
        test_flat = test_samples_subset.reshape(-1, seq_len * input_dim)
        
        # Define forward function: computes total reconstruction error (MSE) per sequence
        def flat_model_forward(x_flat):
            x_3d = x_flat.reshape(-1, seq_len, input_dim)
            x_tensor = torch.tensor(x_3d, dtype=torch.float32).to(self.device)
            with torch.no_grad():
                reconstructed = self.model(x_tensor)
                # Compute MSE per sequence (average over seq_len and input_dim)
                mse = torch.mean((reconstructed - x_tensor) ** 2, dim=[1, 2])
            return mse.cpu().numpy().reshape(-1, 1)

        explainer = shap.KernelExplainer(flat_model_forward, bg_flat)
        shap_values = explainer.shap_values(test_flat)
        
        # Reshape SHAP values back to 3D: (num_test, seq_len, input_dim)
        shap_3d = shap_values[0].reshape(-1, seq_len, input_dim)
        
        # Aggregate SHAP values across samples and time steps
        mean_shap = np.mean(np.abs(shap_3d), axis=(0, 1))

        # Sort features by importance
        indices = np.argsort(mean_shap)
        sorted_features = [self.feature_names[i] for i in indices]
        sorted_shap = mean_shap[indices]
        
        # Plot and save
        plt.figure(figsize=(10, 6))
        plt.barh(range(len(sorted_features)), sorted_shap, align='center', color='skyblue')
        plt.yticks(range(len(sorted_features)), sorted_features)
        plt.xlabel('Mean Absolute SHAP Value (Anomaly Attribution)')
        plt.title('SHAP Feature Importance for Anomaly Detection')
        plt.tight_layout()
        plt.savefig("SHAP_Feature_Importance.png")
        print("SHAP analysis completed. Plot saved to 'SHAP_Feature_Importance.png'.")

class IOTSimulation:
    def __init__(self, file_path):
        self.file_path = file_path
        self.edge_nodes = []
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        
        # Split raw dataframe into Train (70%) and Test (30%) first
        self.raw_df = pd.read_csv(self.file_path)
        raw_target = 'Label' if 'Label' in self.raw_df.columns else self.raw_df.columns[-1]
        df_train, df_test = train_test_split(
            self.raw_df, test_size=0.30, random_state=42, stratify=self.raw_df[raw_target]
        )
        df_train = df_train.reset_index(drop=True)
        df_test = df_test.reset_index(drop=True)
        
        # Fit preprocess on raw train
        dp = preprocess_data()
        dp.fit(df_train, k=25)
        self.feature_names = dp.selected_features
        
        # Transform Train and Test splits
        clean_df_train, X_train_full, y_train_full = dp.transform(df_train)
        clean_df_test, X_test_full, y_test_full = dp.transform(df_test)
        
        print(f"Train preprocessed data: X={X_train_full.shape}, y={y_train_full.shape}")
        print(f"Test preprocessed data: X={X_test_full.shape}, y={y_test_full.shape}")
        
        # Split Train (Part A) into Train-Sub (85%) and Validation Threshold Tuning (15%)
        indices = np.arange(len(X_train_full))
        idx_train_sub, idx_val_thresh = train_test_split(
            indices, test_size=0.15, random_state=42, stratify=y_train_full
        )
        
        X_train_sub = X_train_full[idx_train_sub]
        y_train_sub = y_train_full[idx_train_sub]
        clean_df_train_sub = clean_df_train.iloc[idx_train_sub].reset_index(drop=True)
        
        self.X_val_thresh = X_train_full[idx_val_thresh]
        self.y_val_thresh = y_train_full[idx_val_thresh]
        
        # Partition Train-Sub into A.1 and A.2 for Edge nodes
        split_idx = len(X_train_sub) // 2
        X_half1 = X_train_sub[:split_idx]
        y_half1 = y_train_sub[:split_idx]
        clean_df_half1 = clean_df_train_sub.iloc[:split_idx].reset_index(drop=True)
        
        X_half2 = X_train_sub[split_idx:]
        y_half2 = y_train_sub[split_idx:]
        clean_df_half2 = clean_df_train_sub.iloc[split_idx:].reset_index(drop=True)
        
        # Create Edge nodes
        edge1 = Edge(1, "Sensor 1", clean_df_half1, X_half1, y_half1)
        edge2 = Edge(2, "Sensor 2", clean_df_half2, X_half2, y_half2)
        self.edge_nodes.extend([edge1, edge2])
        
        # Partition Test (Part B) into B.1, B.2, B.3 using StratifiedKFold (Test partition is 100% untouched)
        skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
        folds = list(skf.split(X_test_full, y_test_full))
        
        # Fold 1 -> Part B.1 (Gateway)
        _, test_idx1 = folds[0]
        self.X_part1 = X_test_full[test_idx1]
        self.y_part1 = y_test_full[test_idx1]
        
        # Fold 2 -> Part B.2 (Fog)
        _, test_idx2 = folds[1]
        self.X_part2 = X_test_full[test_idx2]
        self.y_part2 = y_test_full[test_idx2]
        
        # Fold 3 -> Part B.3 (Cloud)
        _, test_idx3 = folds[2]
        self.X_part3 = X_test_full[test_idx3]
        self.y_part3 = y_test_full[test_idx3]
        
        # Save full test split for XAI
        self.X_test_full = X_test_full
        self.y_test_full = y_test_full
        
        self.gateway_nodes = [
            Gateway(1,"Bridge 1")
        ]

        self.fog_nodes = [
            Fog(1, "Fog Layer 1")
        ]

        self.proxy_nodes = [
            Proxy(1,"Proxy Layer 1")
        ]

        self.cloud_nodes = [
            Cloud(1,"Cloud Layer 1")
        ]
        
        # Connecting the layers
        for edge in self.edge_nodes:
            self.gateway_nodes[0].add_child(edge)

        self.fog_nodes[0].add_child(self.gateway_nodes[0])

        self.proxy_nodes[0].add_child(self.fog_nodes[0])

        self.cloud_nodes[0].add_child(self.proxy_nodes[0])

    def run(self, num_rounds=5):
        gc.collect()
        torch.cuda.empty_cache()
        
        for r in range(1, num_rounds + 1):
            print(f"\n========== Federated Round {r}/{num_rounds} START ==========")

            # Step 1: Edge training
            for edge in self.edge_nodes:
                edge.process_data()
                edge.send_model_weights()

            # Step 2: Gateways forward data to Fog
            for gateway in self.gateway_nodes:
                gateway.process_data()

            # Step 3: Fog aggregates weights
            for fog_node in self.fog_nodes:
                fog_node.process_data()
                fog_node.send_global_weights()

            # Step 4: Proxy forwards to Cloud
            for proxy in self.proxy_nodes:
                proxy.process_data()

            # Step 5: Cloud aggregates global model
            for cloud in self.cloud_nodes:
                cloud.process_data()

            print(f"========== Federated Round {r}/{num_rounds} END ==========\n")

        # Saving the Global model
        final_model = self.cloud_nodes[0].global_model
        torch.save(final_model, "Global_Model_Final.pth")
        print("Global model saved!")

        self.app_node = Application(
            node_id=1, 
            name="Application Layer 1", 
            model_path="Global_Model_Final.pth", 
            X_test=self.X_test_full, 
            y_test=self.y_test_full,
            feature_names=self.feature_names
        )
        self.app_node.add_child(self.cloud_nodes[0])

    def compute_anomaly_threshold(self, model):
        model.to(self.device)
        model.eval()
        errors = []
        criterion = nn.MSELoss(reduction='none')
        
        # Extract normal training samples from both Edge nodes
        normal_samples = []
        for edge in self.edge_nodes:
            mask = (edge.y == 0)
            normal_samples.append(edge.X[mask])
        
        all_normal = np.concatenate(normal_samples, axis=0)
        
        # Limit to 5000 samples to prevent memory/computation issues
        if len(all_normal) > 5000:
            indices = np.random.choice(len(all_normal), 5000, replace=False)
            all_normal = all_normal[indices]
            
        # Create normal sequences
        seq_len = SEQUENCE_LENGTH
        sequences = []
        for i in range(len(all_normal) - seq_len + 1):
            sequences.append(all_normal[i:i+seq_len])
        sequences = np.array(sequences)
        
        if len(sequences) == 0:
            print("[Warning] No normal training sequences found. Defaulting mean to 0.5, std to 0.1")
            return 0.5, 0.1
            
        # Compute reconstruction error per sequence
        batch_size = 128
        with torch.no_grad():
            for i in range(0, len(sequences), batch_size):
                batch_seq = sequences[i:i+batch_size]
                batch_tensor = torch.tensor(batch_seq, dtype=torch.float32).to(self.device)
                reconstructed = model(batch_tensor)
                mse = criterion(reconstructed, batch_tensor).mean(dim=[1, 2])
                errors.extend(mse.cpu().numpy())
                
        errors = np.array(errors)
        mean_err = np.mean(errors)
        std_err = np.std(errors)
        print(f"[Threshold Calculation] Mean training reconstruction error: {mean_err:.6f}, Std: {std_err:.6f}")
        return mean_err, std_err

    def create_sequences_with_labels(self, X, y, seq_len=10):
        sequences = []
        labels = []
        for i in range(len(X) - seq_len + 1):
            sequences.append(X[i:i+seq_len])
            labels.append(np.max(y[i : i + seq_len]))
        return np.array(sequences), np.array(labels)

    def optimize_threshold(self, model, mean_err, std_err):
        model.to(self.device)
        model.eval()
        
        # Generate validation sequences
        X_seq, y_seq = self.create_sequences_with_labels(self.X_val_thresh, self.y_val_thresh, seq_len=SEQUENCE_LENGTH)
        X_tensor = torch.tensor(X_seq, dtype=torch.float32).to(self.device)
        y_true = np.array(y_seq)
        
        criterion = nn.MSELoss(reduction='none')
        mse_list = []
        batch_size = 128
        with torch.no_grad():
            for i in range(0, len(X_tensor), batch_size):
                batch_tensor = X_tensor[i:i+batch_size]
                reconstructed = model(batch_tensor)
                mse = criterion(reconstructed, batch_tensor).mean(dim=[1, 2])
                mse_list.extend(mse.cpu().numpy())
        mse_errors = np.array(mse_list)
        
        multipliers = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]
        precisions = []
        recalls = []
        f1s = []
        bal_accs = []
        
        best_f1 = -1.0
        best_multiplier = 2.0
        best_threshold = mean_err + 2.0 * std_err
        best_recall = 0.0
        
        print("\n----- Threshold Optimization Sweep (Tuning Set) -----")
        print(f"{'Multiplier':<12}{'Threshold':<12}{'Precision':<10}{'Recall':<10}{'F1-Score':<10}{'Balanced Acc':<14}")
        print("-" * 68)
        
        from sklearn.metrics import precision_recall_fscore_support, balanced_accuracy_score
        for m in multipliers:
            thresh = mean_err + m * std_err
            preds = (mse_errors > thresh).astype(int)
            
            # Compute metrics for class 1 (anomaly)
            precision, recall, f1, _ = precision_recall_fscore_support(y_true, preds, average='binary', pos_label=1, zero_division=0)
            bal_acc = balanced_accuracy_score(y_true, preds)
            
            precisions.append(precision)
            recalls.append(recall)
            f1s.append(f1)
            bal_accs.append(bal_acc)
            
            print(f"{m:<12.1f}{thresh:<12.6f}{precision:<10.4f}{recall:<10.4f}{f1:<10.4f}{bal_acc:<14.4f}")
            
            # Select multiplier that maximizes F1-Score
            if f1 > best_f1:
                best_f1 = f1
                best_multiplier = m
                best_threshold = thresh
                best_recall = recall
                
        print(f"\n[Optimization] Selected Best Multiplier: {best_multiplier}σ")
        print(f"[Optimization] Threshold value: {best_threshold:.6f}")
        print(f"[Optimization] Validation F1-Score: {best_f1:.4f}")
        print(f"[Optimization] Validation Recall: {best_recall:.4f}")
        
        # Save Threshold Tuning Curves plot
        plt.figure(figsize=(10, 6))
        plt.plot(multipliers, precisions, label='Precision', marker='o', color='green', linewidth=1.5)
        plt.plot(multipliers, recalls, label='Recall', marker='s', color='orange', linewidth=1.5)
        plt.plot(multipliers, f1s, label='F1-Score', marker='^', color='blue', linewidth=2)
        plt.axvline(best_multiplier, color='black', linestyle='--', label=f'Optimal Multiplier ({best_multiplier}σ)')
        plt.xlabel('Multiplier (σ)')
        plt.ylabel('Score')
        plt.title('Threshold Multiplier Sweep vs Evaluation Metrics')
        plt.grid(True)
        plt.legend()
        plt.tight_layout()
        plt.savefig('Threshold_Tuning_Curves.png')
        plt.close()
        print("[Plot] Threshold tuning curves saved to 'Threshold_Tuning_Curves.png'.")
        
        return best_threshold

    def testing_part(self):
        print("\n========== TESTING PHASE START ==========")
        
        # Fetch the cloud layer's global model
        final_model = self.cloud_nodes[0].global_model
        if final_model is None:
            print("[Error] No global model found. Run the simulation first.")
            return
            
        # Compute threshold dynamically
        mean_err, std_err = self.compute_anomaly_threshold(final_model)
        
        # Optimize threshold using the clean tuning subset
        self.anomaly_threshold = self.optimize_threshold(final_model, mean_err, std_err)
        
        # Testing at Gateway Level with B.1
        print(f"\n----- Testing at Gateway Level (using Test Split B.1) -----")
        for gateway in self.gateway_nodes:
            gateway.eval(None, self.X_part1, self.y_part1, self.anomaly_threshold)
    
        gc.collect()
        torch.cuda.empty_cache()
        
        # Testing at Fog Level with B.2
        print(f"\n----- Testing at Fog Level (using Test Split B.2) -----")
        for fog in self.fog_nodes:
            fog.eval(None, self.X_part2, self.y_part2, self.anomaly_threshold)
    
        gc.collect()
        torch.cuda.empty_cache()
        
        # Testing at Cloud Level with B.3
        print(f"\n----- Testing at Cloud Level (using Test Split B.3) -----")
        for cloud in self.cloud_nodes:
            cloud.eval(None, self.X_part3, self.y_part3, self.anomaly_threshold)
            
        # Calculate reconstruction errors for B.3 to plot the distribution curve
        X_test_seq, y_test_seq = self.create_sequences_with_labels(self.X_part3, self.y_part3, seq_len=SEQUENCE_LENGTH)
        X_test_tensor = torch.tensor(X_test_seq, dtype=torch.float32).to(self.device)
        y_test_true = np.array(y_test_seq)
        
        criterion = nn.MSELoss(reduction='none')
        test_errors = []
        batch_size = 128
        with torch.no_grad():
            for i in range(0, len(X_test_tensor), batch_size):
                batch_tensor = X_test_tensor[i:i+batch_size]
                reconstructed = final_model(batch_tensor)
                mse = criterion(reconstructed, batch_tensor).mean(dim=[1, 2])
                test_errors.extend(mse.cpu().numpy())
        test_errors = np.array(test_errors)
        
        # Separate benign and attack errors
        benign_errors = test_errors[y_test_true == 0]
        attack_errors = test_errors[y_test_true == 1]
        
        plt.figure(figsize=(10, 6))
        plt.hist(benign_errors, bins=50, alpha=0.6, label='Benign sequences', color='blue', density=True)
        plt.hist(attack_errors, bins=50, alpha=0.6, label='Attack sequences', color='red', density=True)
        plt.axvline(self.anomaly_threshold, color='black', linestyle='--', linewidth=1.5, label=f'Threshold ({self.anomaly_threshold:.6f})')
        plt.xlabel('Reconstruction MSE')
        plt.ylabel('Density')
        plt.title('Reconstruction Error Distribution (Benign vs Attack)')
        plt.grid(True)
        plt.legend()
        plt.tight_layout()
        plt.savefig('Reconstruction_Error_Distribution.png')
        plt.close()
        print("[Plot] Reconstruction error distribution saved to 'Reconstruction_Error_Distribution.png'.")
    
        gc.collect()
        torch.cuda.empty_cache()
    
        print("\n========== TESTING PHASE END ==========")

    def XAI(self):
        self.app_node.load_model_and_data()
        self.app_node.run_xai()

if __name__ == "__main__":
    dataset_path = "wustl_hdrl_2024.csv"
    if not os.path.exists(dataset_path):
        dataset_path = "/content/wustl_hdrl_2024.csv"
        
    sim = IOTSimulation(dataset_path)
    print("\n----- Training -----")
    sim.run()
    
    print(f"\n----- Testing -----")
    sim.testing_part()

    print(f"\n----- Application (XAI) -----")
    sim.XAI()